export const PackageCardData = [
  {
    header: "Scheduled Packages",
    content: [
      {
        cardImage: "images/servicePage/basic-service.jpg",
        title: "Basic Service",
        desc: "• 1000 Kms or 1 Month Warranty   • Every 5000 Kms or 3 Months (Recommended)",
        bullets: [
          "Wiper Fluid Replacement",
          "Battery Water Top Up",
          "Car Wash",
          "Interior Vacuuming ( Carpet & Seats )",
          "Engine Oil Replacement",
          "Oil Filter Replacement",
          "Air Filter Cleaning",

          "Smartcool Coolant Top Up",
          "Heater/Spark Plugs Checking",
        ],
        icon: "images/servicePage/bullet-point.svg",
        price: 3499,
        discount: 20,
        timeTaken: 4,
      },
      {
        cardImage: "images/servicePage/periodic/img2.jpg",
        title: "Standard Service",
        desc: "• 1000 Kms or 1 Month Warranty    • Every 10,000 Kms or 6 Months (Recommended)",
        bullets: [
          "Car Scanning",
          "Wiper Fluid Replacement",
          "Battery Water Top up",
          "Car Wash",
          "Interior Vacuuming ( Carpet & Seats )",
          "Rear Brake Shoes Serviced",
          "Front Brake Pads Serviced",

          "Engine Oil Replacement",
          "Oil Filter Replacement",
          "Air Filter Replacement",
          "Fuel Filter Checking",
          "Smartcool Coolant Top Up",
          "Heater/Spark Plugs Checking",
          "Brake Fluid Top Up",
          "AC Filter Cleaning",
        ],
        icon: "images/servicePage/bullet-point.svg",
        price: 4809,
        discount: 20,
        timeTaken: 6,
      },
      {
        cardImage: "images/servicePage/periodic/img3.jpg",
        title: "Comprehensive Service",
        desc: "• 1000 Kms or 1 Month Warranty    • Every 20,000 Kms or 12 Months (Recommended)",
        bullets: [
          "AC Filter Replacement",
          "Fuel Filter Checking",
          "Car Scanning",
          "Wiper Fluid Replacement",
          "Battery Water Top up",
          "Car Wash",
          "Interior Vacuuming ( Carpet & Seats )",

          "Rear Brake Shoes Serviced",
          "Front Brake Pads Serviced",
          "Wheel Balancing",
          "Wheel Alignment",
          "Tyre Rotation",
          "Engine Oil Replacement",
          "Oil Filter Replacement",
          "Air Filter Replacement",
          "Throttle Body Cleaning",
          "Gear Oil Top Up",
          "Smartcool Coolant Top Up",
          "Heater/Spark Plugs Checking",
          "Brake Fluid Top Up",
          "Engine Flushing",
        ],
        icon: "images/servicePage/bullet-point.svg",
        price: 6239,
        discount: 20,
        timeTaken: 4,
      },
    ],
  },
  {
    header: "Brake Maintenance",
    content: [
      {
        cardImage: "images/servicePage/periodic/img4.jpg",
        title: "Front Brake Pads",
        desc: "• 1 Month Warranty    • Every 20000 Kms or 12 Months (Recommended)",
        bullets: [
          "Opening & Fitting of Brakes",
          "Front Brake Pads Replacement (GoMechanic)",
          "Front Brake Disc Cleaning",
        ],
        icon: "images/servicePage/bullet-point.svg",
        price: 4679,
        discount: 20,
        timeTaken: 3,
      },
      {
        cardImage: "images/servicePage/periodic/img5.jpg",
        title: "Rear Brake Shoes",
        desc: "• 1 Month Warranty    • Every 20000 Kms or 12 Months (Recommended)",
        bullets: [
          "Opening & Fitting of Brakes",
          "Rear Brake Shoes Replacement (OES)",
          "Rear Brake Disc Cleaning",
        ],
        icon: "images/servicePage/bullet-point.svg",
        price: 2999,
        discount: 20,
        timeTaken: 3,
      },
      {
        cardImage: "images/servicePage/periodic/img6.jpg",
        title: "Front Brake Pads",
        desc: "• 1 Month Warranty    • Corrosion Resistance",
        bullets: [
          "Front Brake Disc Replacement (Single OES Unit)",
          "Opening & Fitting of Front Brake Disc",
          "Reduces Vibrations and Brake Noises",
          "Increases Brake Life & Safety",
          "Free Pickup & Drop",
        ],
        icon: "images/servicePage/bullet-point.svg",
        price: 2280,
        discount: 20,
        timeTaken: 3,
      },
      {
        cardImage: "images/servicePage/periodic/img7.jpg",
        title: "Disc Turning",
        desc: "• 1 Month Warranty on Labour",
        bullets: [
          "Opening & Fitting + Inspection Of Below Items",
          "Resurfacing of Brake Discs/Rotors",
          "Applicable For Set of 2 Discs (2 Tyres)",
        ],
        icon: "images/servicePage/bullet-point.svg",
        price: 839,
        discount: 20,
        timeTaken: 3,
      },
      {
        cardImage: "images/servicePage/periodic/img8.jpg",
        title: "Handbrake Wire Replacement",
        desc: "• Recommended : In Case Handbrake Stops Working",
        bullets: [
          "Handbrake Wire Replacement (Single OES Unit)",
          "Brake Drum Inspection",
          "Electronic Parking Brake Cost Additonal",
          "Wheel Cylinder, Ratchet, Clamps Cost Additional",
          "Free Pickup & Drop",
        ],
        icon: "images/servicePage/bullet-point.svg",
        price: 4679,
        discount: 20,
        timeTaken: 3,
      },
      {
        cardImage: "images/servicePage/periodic/img9.jpg",
        title: "Brake Drums Turning",
        desc: "• 1 Month Warranty    • Recommended : In Case of Screeching Noise from Brakes",
        bullets: [
          "Brake Drums Turning",
          "Opening & Fitting of Brake Drums",
          "Refacing of Brake Drums",
          "Applicable for Set of 2 Drums",
          "Free Pickup & Drop",
        ],
        icon: "images/servicePage/bullet-point.svg",
        price: 1079,
        discount: 20,
        timeTaken: 3,
      },
    ],
  },
];
